/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-02 18:29:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.lang.Math;
import com.google.gson.Gson;
import gestoracademico.Usuario;
import gestoracademico.Asignatura;
import gestoracademico.DBManager;

public final class recomendador_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/barraSuperiorEst.jsp", Long.valueOf(1696956840428L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("gestoracademico.Asignatura");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.google.gson.Gson");
    _jspx_imports_classes.add("gestoracademico.Usuario");
    _jspx_imports_classes.add("java.lang.Math");
    _jspx_imports_classes.add("gestoracademico.DBManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title> AMIUP: Recomendador </title>\r\n");
      out.write("        <link href=\"");
      out.print( request.getContextPath() );
      out.write("/VISUAL/inicio.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("        <link href=\"");
      out.print( request.getContextPath() );
      out.write("/VISUAL/barraSuperior.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("        <link href=\"");
      out.print( request.getContextPath() );
      out.write("/VISUAL/estudiante.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("        <script src=\"https://d3js.org/d3.v6.min.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        ");
 Usuario usuario = new Usuario();
        usuario= (Usuario)session.getAttribute("Usuario"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 Double suma_nota_pre = 0.00;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 Double nota_media_pre = 0.00;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
boolean suspenso = false; 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 String nombre_asignatura = request.getParameter("asignatura");
        
        Gson gson = new Gson();
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 List<Asignatura> preRequisitos = (List<Asignatura>) request.getAttribute("Prerrequisitos"); 
            
            
        String jsonPreRrequisitos = gson.toJson(preRequisitos);    
        
      out.write("\r\n");
      out.write("        ");
 List<Asignatura> postRequisitos = (List<Asignatura>) request.getAttribute("PostRequisitos"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 List<Asignatura> notaHistTitulacion = (List<Asignatura>) request.getAttribute("NOTA MEDIA POR ANIO TITULACION");  
        
        String jsonNotaHistTitulacion = gson.toJson(notaHistTitulacion);
        
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
 List<Asignatura> participacionHistTitulacion = (List<Asignatura>) request.getAttribute("PARTICIPACION MEDIA POR ANIO TITULACION");
        
        String jsonParticipacionHistTitulacion = gson.toJson(participacionHistTitulacion);    
                    
        
      out.write("\r\n");
      out.write("        ");
 List<Asignatura> asistenciaHistTitulacion = (List<Asignatura>) request.getAttribute("ASISTENCIA MEDIA POR ANIO TITULACION"); 
                    
        String jsonAsistenciaHistTitulacion = gson.toJson(asistenciaHistTitulacion); 
                    
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 Asignatura asignaturaClick = new Asignatura();
        asignaturaClick = (Asignatura)request.getAttribute("Asignatura click");

        String jsonAsignaturaClick = gson.toJson(asignaturaClick);
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 Asignatura infoAsigAnio = new Asignatura();
        infoAsigAnio = (Asignatura)request.getAttribute("Info Asignatura Fecha"); 
        
        String jsoninfoAsigAnio = gson.toJson(infoAsigAnio);
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div>");
      out.write("<nav class=\"barraSuperior\">\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li id=\"login\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/inicioSesion\">");
      out.print(usuario.getNombre());
      out.write("</a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/estudianteCompleto\">Ver todas las asignaturas</a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/estudiante\">Inicio</a></li>\r\n");
      out.write("        <li class=\"izq\"> AMIUP </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</nav>");
      out.write(" </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"principalPrueba\">\r\n");
      out.write("            <div class=\"padrePrueba\">\r\n");
      out.write("                <h2>Prerrequisitos</h2>\r\n");
      out.write("                <div class=\"hijoPrueba\">\r\n");
      out.write("                    ");
if(!preRequisitos.isEmpty()){
      out.write(" \r\n");
      out.write("                        ");
for(Asignatura asignatura: preRequisitos){
      out.write("\r\n");
      out.write("                            <div class=\"asignaturaPrueba\">\r\n");
      out.write("                                <h3>");
      out.print(asignatura.getNombre());
      out.write("</h3>\r\n");
      out.write("                                ");
if((Double.parseDouble(asignatura.getNota())) >= 9){ 
      out.write("\r\n");
      out.write("                                    <div class=\"notaPrueba\" style=\"background-color: green;\">");
      out.print( (Double.parseDouble(asignatura.getNota())) );
      out.write("</div>\r\n");
      out.write("                                ");
}else if((Double.parseDouble(asignatura.getNota())) >= 7 && (Double.parseDouble(asignatura.getNota())) < 9){ 
      out.write("\r\n");
      out.write("                                    <div class=\"notaPrueba\" style=\"background-color: yellow;\">");
      out.print( (Double.parseDouble(asignatura.getNota())) );
      out.write("</div>\r\n");
      out.write("                                ");
}else if((Double.parseDouble(asignatura.getNota())) >= 5 && (Double.parseDouble(asignatura.getNota())) < 7){ 
      out.write("\r\n");
      out.write("                                    <div class=\"notaPrueba\" style=\"background-color: orange;\">");
      out.print( (Double.parseDouble(asignatura.getNota())) );
      out.write("</div>\r\n");
      out.write("                                ");
}else if((Double.parseDouble(asignatura.getNota())) < 5){ 
      out.write("\r\n");
      out.write("                                    <div class=\"notaPrueba\" style=\"background-color: red;\">");
      out.print( (Double.parseDouble(asignatura.getNota())) );
      out.write("</div>\r\n");
      out.write("                                ");
}
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
if(asignatura.getNota() != null){
                                suma_nota_pre = suma_nota_pre + Double.parseDouble(asignatura.getNota());
                            } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            ");
if((Double.parseDouble(asignatura.getNota())) < 5){
                                suspenso = true;
                            } 
      out.write("\r\n");
      out.write("                        ");
}
      out.write(" \r\n");
      out.write("\r\n");
      out.write("                        ");
nota_media_pre = suma_nota_pre/preRequisitos.size();
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");
if(asignaturaClick.getNota() != null){ 
      out.write("\r\n");
      out.write("                            ");
if((Double.parseDouble(asignaturaClick.getNota())) < 5 && suspenso == true){ 
      out.write("\r\n");
      out.write("                                <p class=\"info\">Para cursar de manera segura ");
      out.print(asignaturaClick.getNombre());
      out.write(", antes deberia aprobar los prerrequisitos.%></p>\r\n");
      out.write("                            ");
}else if((Double.parseDouble(asignaturaClick.getNota())) >= 5 && suspenso == true){ 
      out.write(" \r\n");
      out.write("                                <p class=\"info\"> <b>Ha aprobado ");
      out.print( asignaturaClick.getNombre());
      out.write(" sin haber superado todos los prerrequisitos.</b></p>\r\n");
      out.write("                            ");
} else if((Double.parseDouble(asignaturaClick.getNota())) < 5 && suspenso == false){ 
      out.write("\r\n");
      out.write("                                <p class=\"info\"><b>Ha superado todos los prerrequisitos. Es momento de volver a cursar ");
      out.print(asignaturaClick.getNombre());
      out.write(".</b></p>\r\n");
      out.write("                            ");
} else{ 
      out.write(" \r\n");
      out.write("                                <p class=\"info\"><b> Todos los prerrequisitos aprobados.</b></p>\r\n");
      out.write("                            ");
}
      out.write("\r\n");
      out.write("                        ");
 }else{ 
      out.write("\r\n");
      out.write("                            ");
if(suspenso == true){
      out.write(" \r\n");
      out.write("                                <p class=\"info\"><b>No es recomendable cursar ");
      out.print(nombre_asignatura);
      out.write(". Antes de ello se le recominda aprobar todos los prerrequisitos.</b></p>\r\n");
      out.write("                            ");
} else{ 
      out.write(" \r\n");
      out.write("                                <p class=\"info\">Segun las notas en los distintos prerrequisitos, se ha llegado a la siguiente conclusion: </p>\r\n");
      out.write("                                <p class=\"info\"><b>Nota media (sobre 10) -> </b>");
      out.print(nota_media_pre);
      out.write(".</p>\r\n");
      out.write("                                \r\n");
      out.write("                                ");
 if(nota_media_pre >= 7){
      out.write("\r\n");
      out.write("                                    <p class=\"info\"><b>Muy recomendable cursar ");
      out.print(nombre_asignatura);
      out.write(".</b></p>\r\n");
      out.write("                                ");
}else if(nota_media_pre < 7 && nota_media_pre >= 6){
      out.write("\r\n");
      out.write("                                    <p class=\"info\"><b>Es recomendable cursar ");
      out.print(nombre_asignatura);
      out.write(".</b></p>\r\n");
      out.write("                                ");
}else if(nota_media_pre >= 5 && nota_media_pre < 6){
      out.write("\r\n");
      out.write("                                    <p class=\"info\"><b>Poco recomendable cursar ");
      out.print(nombre_asignatura);
      out.write(".</b></p>\r\n");
      out.write("                                ");
}
      out.write("\r\n");
      out.write("                            ");
}
      out.write("    \r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    ");
 }else{   
      out.write("\r\n");
      out.write("                        <p class=\"info\"> Esta asignatura no tiene prerrequisitos. Puede cursarla en cualquier momento.</p>\r\n");
      out.write("                    ");
}
      out.write(" \r\n");
      out.write("\r\n");
      out.write("                    <div class=\"hijoPrueba\">\r\n");
      out.write("                        <canvas id=\"pre\"></canvas>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"padrePrueba\" id=\"centro\">\r\n");
      out.write("                <h2 id=\"tituloCentro\">");
      out.print(nombre_asignatura);
      out.write('(');
      out.print(asignaturaClick.getNota());
      out.write(')');
      out.write('(');
      out.print(asignaturaClick.getAsistencia());
      out.write(')');
      out.write('(');
      out.print(asignaturaClick.getParticipacion());
      out.write(")</h2>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"hijoPrueba\">\r\n");
      out.write("                    <canvas id=\"notasComp\"></canvas>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"hijoPrueba\">\r\n");
      out.write("                    <canvas id=\"notas\"></canvas>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"hijoPrueba\">\r\n");
      out.write("                    <canvas id=\"asistencia\"></canvas>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"hijoPrueba\">\r\n");
      out.write("                    <canvas id=\"participacion\"></canvas>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"padrePrueba\" >\r\n");
      out.write("                <h2>Postrequisitos</h2>\r\n");
      out.write("                <div class=\"hijoPrueba\">\r\n");
      out.write("                    ");
if(!postRequisitos.isEmpty()){ 
      out.write(" \r\n");
      out.write("                        ");
for(Asignatura asignatura: postRequisitos){
      out.write("\r\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/recomendador?asignatura=");
      out.print(asignatura.getNombre());
      out.write("&id=");
      out.print(asignatura.getId());
      out.write("\" class=\"asignaturaPrueba\">\r\n");
      out.write("                                <h3>");
      out.print(asignatura.getNombre());
      out.write("</h3>\r\n");
      out.write("                                ");
if((Double.parseDouble(asignatura.getNota())) >= 9){ 
      out.write("\r\n");
      out.write("                                    <div class=\"notaPrueba\" style=\"background-color: green;\">");
      out.print( (Double.parseDouble(asignatura.getNota())) );
      out.write("</div>\r\n");
      out.write("                                ");
}else if((Double.parseDouble(asignatura.getNota())) >= 7 && (Double.parseDouble(asignatura.getNota())) < 9){ 
      out.write("\r\n");
      out.write("                                    <div class=\"notaPrueba\" style=\"background-color: yellow;\">");
      out.print( (Double.parseDouble(asignatura.getNota())) );
      out.write("</div>\r\n");
      out.write("                                ");
}else if((Double.parseDouble(asignatura.getNota())) >= 5 && (Double.parseDouble(asignatura.getNota())) < 7){ 
      out.write("\r\n");
      out.write("                                    <div class=\"notaPrueba\" style=\"background-color: orange;\">");
      out.print( (Double.parseDouble(asignatura.getNota())) );
      out.write("</div>\r\n");
      out.write("                                ");
}else if((Double.parseDouble(asignatura.getNota())) < 5){ 
      out.write("\r\n");
      out.write("                                    <div class=\"notaPrueba\" style=\"background-color: red;\">");
      out.print( (Double.parseDouble(asignatura.getNota())) );
      out.write("</div>\r\n");
      out.write("                                ");
}
      out.write("\r\n");
      out.write("                            </a>\r\n");
      out.write("                        ");
}
      out.write("\r\n");
      out.write("                        ");
if(asignaturaClick.getNota() != null){
      out.write("\r\n");
      out.write("                            ");
 if((Double.parseDouble(asignaturaClick.getNota())) >= 5 ){
      out.write("\r\n");
      out.write("                                <p class=\"info\">Cumple uno de los requisitos para cursar los distintos postrequisitos.<br>\r\n");
      out.write("                                    Para mas informacion pulse sobre la asignatura.\r\n");
      out.write("                                </p>\r\n");
      out.write("                            \r\n");
      out.write("                            ");
}else{
      out.write("\r\n");
      out.write("                                <p class=\"info\">Antes deberia cursar ");
      out.print(asignaturaClick.getNombre());
      out.write(" para matricular estas asignaturas.</p>\r\n");
      out.write("                            ");
} 
      out.write("\r\n");
      out.write("                        ");
} else { 
      out.write("  \r\n");
      out.write("                            <p> No hay nota existente de ");
      out.print(asignaturaClick.getNombre());
      out.write(". Para cursar los postrequisitos deberia superar esta asignatura.</p>       \r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("                    ");
}else{ 
      out.write("\r\n");
      out.write("                        <p class=\"info\">Esta asignatura no tiene postrequisitos.</p>\r\n");
      out.write("                    ");
} 
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            //GRAFICO DE BARRAS DOBLE QUE MUESTRA UNA COMPARACION DEL ALUMNO CON LA TITULACION\r\n");
      out.write("            document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("                var jsonInfoAsigAnio = '");
      out.print(jsoninfoAsigAnio);
      out.write("';\r\n");
      out.write("                var infoAsigAnio = JSON.parse(jsonInfoAsigAnio);\r\n");
      out.write("              \r\n");
      out.write("                var jsonAsignaturaClick = '");
      out.print(jsonAsignaturaClick);
      out.write("';\r\n");
      out.write("                var asignaturaClick = JSON.parse(jsonAsignaturaClick);\r\n");
      out.write("                \r\n");
      out.write("                var data = {\r\n");
      out.write("                    labels: ['Nota', 'Asistencia', 'Participacion'],\r\n");
      out.write("                    datasets: [\r\n");
      out.write("                        {\r\n");
      out.write("                            label: 'Alumno',\r\n");
      out.write("                            backgroundColor: 'rgba(54, 162, 235, 0.6)',\r\n");
      out.write("                            borderColor: 'rgba(54, 162, 235, 1)',\r\n");
      out.write("                            borderWidth: 1,\r\n");
      out.write("                            data: [asignaturaClick.nota, asignaturaClick.asistencia,asignaturaClick.participacion],\r\n");
      out.write("                        },\r\n");
      out.write("                        {\r\n");
      out.write("                            label: 'Clase',\r\n");
      out.write("                            backgroundColor: 'rgba(255, 99, 132, 0.6)',\r\n");
      out.write("                            borderColor: 'rgba(255, 99, 132, 1)',\r\n");
      out.write("                            borderWidth: 1,\r\n");
      out.write("                            data: [infoAsigAnio.nota_media, infoAsigAnio.asistencia_media,infoAsigAnio.participacion_media],\r\n");
      out.write("                        }\r\n");
      out.write("                    ]\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                var options = {\r\n");
      out.write("                    responsive: true,\r\n");
      out.write("                    maintainAspectRatio: false,\r\n");
      out.write("                    scales: {\r\n");
      out.write("                        y: {\r\n");
      out.write("                            beginAtZero: true\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                var ctx = document.getElementById('notasComp').getContext('2d');\r\n");
      out.write("                var myChart = new Chart(ctx, {\r\n");
      out.write("                    type: 'bar',\r\n");
      out.write("                    data: data,\r\n");
      out.write("                    options: options\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            //GRAFICO DE TARTA PARA MOSTRAR PRERREQUISITOS\r\n");
      out.write("            document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("                var jsonPreRrequisitos = '");
      out.print(jsonPreRrequisitos);
      out.write("';\r\n");
      out.write("                var preRrequisitos = JSON.parse(jsonPreRrequisitos);\r\n");
      out.write("                \r\n");
      out.write("                console.log(preRrequisitos);\r\n");
      out.write("                var notas = [];\r\n");
      out.write("                var total = 10*preRrequisitos.length;\r\n");
      out.write("                var total_creditos = 0;\r\n");
      out.write("                \r\n");
      out.write("                var suma_nota = 0;\r\n");
      out.write("\r\n");
      out.write("                for (var i = 0; i < preRrequisitos.length; i++) {\r\n");
      out.write("                    var creditos = preRrequisitos[i].creditos;\r\n");
      out.write("                    total_creditos = parseInt(total_creditos)+parseInt(creditos);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                console.log(total_creditos);\r\n");
      out.write("                for (var i = 0; i < preRrequisitos.length; i++) {\r\n");
      out.write("                    var nota = preRrequisitos[i].nota;\r\n");
      out.write("                    suma_nota = parseFloat(suma_nota)+parseFloat(nota);\r\n");
      out.write("                    notas.push(nota);\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                total = total - suma_nota;\r\n");
      out.write("\r\n");
      out.write("                notas.push(total);\r\n");
      out.write("                \r\n");
      out.write("                var data = {\r\n");
      out.write("                    labels: ['Progreso Prerrequisitos'],\r\n");
      out.write("                    datasets: [\r\n");
      out.write("                        {\r\n");
      out.write("                            label: 'Alumno',\r\n");
      out.write("                            backgroundColor: ['rgba(54, 162, 235, 0.6)','rgba(124, 162, 235, 0.6)','rgba(255, 255, 255, 0.6)'],\r\n");
      out.write("                            borderColor: 'rgba(54, 162, 235, 1)',\r\n");
      out.write("                            borderWidth: 1,\r\n");
      out.write("                            data: notas,\r\n");
      out.write("                        }\r\n");
      out.write("                    ]\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                var options = {\r\n");
      out.write("                    responsive: true,\r\n");
      out.write("                    maintainAspectRatio: false,\r\n");
      out.write("                    scales: {\r\n");
      out.write("                        y: {\r\n");
      out.write("                            beginAtZero: true\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                var ctx = document.getElementById('pre').getContext('2d');\r\n");
      out.write("                var myChart = new Chart(ctx, {\r\n");
      out.write("                    type: 'pie',\r\n");
      out.write("                    data: data,\r\n");
      out.write("                    options: options\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            //GRAFICO DE BARRAS QUE MUESTRA LA NOTA MEDIA A LO LARGO DE LOS AÑOS\r\n");
      out.write("            document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("                var notaHistTitulacion = '");
      out.print( jsonNotaHistTitulacion );
      out.write("';\r\n");
      out.write("\r\n");
      out.write("                var datosNotas = JSON.parse(notaHistTitulacion);\r\n");
      out.write("                var anios = [];\r\n");
      out.write("                var notas = []; \r\n");
      out.write("                \r\n");
      out.write("                for (var i = 0; i < datosNotas.length; i++) {\r\n");
      out.write("                    var fecha = datosNotas[i].fecha;\r\n");
      out.write("                    anios.push(fecha);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                for (var i = 0; i < datosNotas.length; i++) {\r\n");
      out.write("                    var nota = datosNotas[i].nota_media;\r\n");
      out.write("                    notas.push(nota);\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                var data = {\r\n");
      out.write("                    labels: anios,\r\n");
      out.write("                    datasets: [{\r\n");
      out.write("                        label: 'Nota media por año',\r\n");
      out.write("                        backgroundColor: 'rgba(54, 162, 235, 0.6)',\r\n");
      out.write("                        borderColor: 'rgba(54, 162, 235, 1)',\r\n");
      out.write("                        borderWidth: 1,\r\n");
      out.write("                        data: notas,\r\n");
      out.write("                    }]\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                var options = {\r\n");
      out.write("                    responsive: true,\r\n");
      out.write("                    maintainAspectRatio: false,\r\n");
      out.write("                    scales: {\r\n");
      out.write("                        y: {\r\n");
      out.write("                            beginAtZero: true\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                var ctx = document.getElementById('notas').getContext('2d');\r\n");
      out.write("                var myChart = new Chart(ctx, {\r\n");
      out.write("                    type: 'bar',\r\n");
      out.write("                    data: data,\r\n");
      out.write("                    options: options\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            //GRAFICO DE BARRAS QUE MUESTRA LA ASISTENCIA MEDIA A LO LARGO DE LOS AÑOS\r\n");
      out.write("            document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("                var asistenciaHistTitulacion = '");
      out.print( jsonAsistenciaHistTitulacion );
      out.write("';\r\n");
      out.write("\r\n");
      out.write("                var datosAsistencia = JSON.parse(asistenciaHistTitulacion);\r\n");
      out.write("                var anios = [];\r\n");
      out.write("                var asistencia = [];\r\n");
      out.write("                \r\n");
      out.write("                for (var i = 0; i < datosAsistencia.length; i++) {\r\n");
      out.write("                    var fecha = datosAsistencia[i].fecha;\r\n");
      out.write("                    anios.push(fecha);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                for (var i = 0; i < datosAsistencia.length; i++) {\r\n");
      out.write("                    var asistenciaNota = datosAsistencia[i].asistencia_media;\r\n");
      out.write("                    asistencia.push(asistenciaNota);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                var data = {\r\n");
      out.write("                    labels: anios,\r\n");
      out.write("                    datasets: [{\r\n");
      out.write("                        label: 'Asitencia media por año',\r\n");
      out.write("                        backgroundColor: 'rgba(54, 162, 235, 0.6)',\r\n");
      out.write("                        borderColor: 'rgba(54, 162, 235, 1)',\r\n");
      out.write("                        borderWidth: 1,\r\n");
      out.write("                        data: asistencia,\r\n");
      out.write("                    }]\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                var options = {\r\n");
      out.write("                    responsive: true,\r\n");
      out.write("                    maintainAspectRatio: false,\r\n");
      out.write("                    scales: {\r\n");
      out.write("                        y: {\r\n");
      out.write("                            beginAtZero: true\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                var ctx = document.getElementById('asistencia').getContext('2d');\r\n");
      out.write("                var myChart = new Chart(ctx, {\r\n");
      out.write("                    type: 'bar',\r\n");
      out.write("                    data: data,\r\n");
      out.write("                    options: options\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            //GRAFICO DE BARRAS QUE MUESTRA LA PARTICIPACION MEDIA A LO LARGO DE LOS AÑOS\r\n");
      out.write("            document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("                var participacionHistTitulacion = '");
      out.print( jsonParticipacionHistTitulacion );
      out.write("';\r\n");
      out.write("\r\n");
      out.write("                var datosParticipacion = JSON.parse(participacionHistTitulacion);\r\n");
      out.write("                var anios = [];\r\n");
      out.write("                var participacion = [];\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                for (var i = 0; i < datosParticipacion.length; i++) {\r\n");
      out.write("                    var fecha = datosParticipacion[i].fecha;\r\n");
      out.write("                    anios.push(fecha);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                for (var i = 0; i < datosParticipacion.length; i++) {\r\n");
      out.write("                    var participacionNota = datosParticipacion[i].participacion_media;\r\n");
      out.write("                    participacion.push(participacionNota);\r\n");
      out.write("                }\r\n");
      out.write("              \r\n");
      out.write("                var data = {\r\n");
      out.write("                    labels: anios,\r\n");
      out.write("                    datasets: [{\r\n");
      out.write("                        label: 'Participacion media por año',\r\n");
      out.write("                        backgroundColor: 'rgba(54, 162, 235, 0.6)',\r\n");
      out.write("                        borderColor: 'rgba(54, 162, 235, 1)',\r\n");
      out.write("                        borderWidth: 1,\r\n");
      out.write("                        data: participacion,\r\n");
      out.write("                    }]\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                var options = {\r\n");
      out.write("                    responsive: true,\r\n");
      out.write("                    maintainAspectRatio: false,\r\n");
      out.write("                    scales: {\r\n");
      out.write("                        y: {\r\n");
      out.write("                            beginAtZero: true\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                var ctx = document.getElementById('participacion').getContext('2d');\r\n");
      out.write("                var myChart = new Chart(ctx, {\r\n");
      out.write("                    type: 'bar',\r\n");
      out.write("                    data: data,\r\n");
      out.write("                    options: options\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("    .principalPrueba{\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: row;       \r\n");
      out.write("        width: 80%;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        margin-left: 10%;\r\n");
      out.write("        margin-top: 100px;\r\n");
      out.write("    }\r\n");
      out.write("    .padrePrueba{\r\n");
      out.write("        position: relative;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        width: 30%;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        row-gap: 10px;\r\n");
      out.write("        border: 5px solid black;\r\n");
      out.write("        background-color: rgb(100, 180, 153);\r\n");
      out.write("    } \r\n");
      out.write("\r\n");
      out.write("    .hijoPrueba{\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        row-gap: 10px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        margin-top:50px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    } \r\n");
      out.write("\r\n");
      out.write("    .asignaturaPrueba{\r\n");
      out.write("        background-color: rgb(133, 234, 148);\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        width: 65%;\r\n");
      out.write("        height: 120px;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-left: 15%;\r\n");
      out.write("    } \r\n");
      out.write("\r\n");
      out.write("    .principalPrueba .padrePrueba h2{\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("        margin-left: 35%;\r\n");
      out.write("        color: #333;\r\n");
      out.write("    } \r\n");
      out.write("\r\n");
      out.write("    .principalPrueba .padrePrueba .hijoPrueba .asignaturaPrueba .notaPrueba{\r\n");
      out.write("        position:static;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        background-color: red;\r\n");
      out.write("        margin-top: 13px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .asignaturaPrueba h3 {\r\n");
      out.write("        padding-top: 20px;\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .info{\r\n");
      out.write("        padding: 15px 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        background-color: rgb(133, 234, 148);\r\n");
      out.write("        color: #333;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("    }   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    #graficoNota_Anio{\r\n");
      out.write("        background-color: white;\r\n");
      out.write("    } \r\n");
      out.write("    #centro{\r\n");
      out.write("        position: relative;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        width: 40%;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        row-gap: 10px;\r\n");
      out.write("        border: 5px solid black;\r\n");
      out.write("    }  \r\n");
      out.write("\r\n");
      out.write("    #tituloCentro{\r\n");
      out.write("        position: relative;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("        margin-left: 18%;\r\n");
      out.write("        color: #333;\r\n");
      out.write("    } \r\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
